import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
  date,
  boolean,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("sessions_user_idx").on(t.userId)],
);

export const userSettings = pgTable("user_settings", {
  userId: integer("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  // Give feedback after at least this many lessons seen…
  minLessons: integer("min_lessons").notNull().default(4),
  // …but never more than this many lessons without feedback.
  maxLessons: integer("max_lessons").notNull().default(8),
  // Hard rule: never more than this many days without handing something back.
  maxGapDays: integer("max_gap_days").notNull().default(14),
  // School days kept between collecting books and handing them back.
  windowDays: integer("window_days").notNull().default(5),
});

export const classes = pgTable(
  "classes",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    subject: text("subject").notNull().default(""),
    yearGroup: text("year_group").notNull().default(""),
    studentCount: integer("student_count").notNull().default(30),
    color: text("color").notNull().default("#D94F26"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("classes_user_idx").on(t.userId)],
);

export const timetableSlots = pgTable(
  "timetable_slots",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    classId: integer("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    dayOfWeek: integer("day_of_week").notNull(), // 1 = Mon … 5 = Fri
    period: integer("period").notNull(), // 1..6
  },
  (t) => [
    uniqueIndex("slots_user_day_period_idx").on(
      t.userId,
      t.dayOfWeek,
      t.period,
    ),
    index("slots_class_idx").on(t.classId),
  ],
);

export const markingPlans = pgTable(
  "marking_plans",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    classId: integer("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("Formative check"),
    // 'auto'   → generated by the smart planner
    // 'manual' → a deadline task created by the teacher
    planType: text("plan_type").notNull().default("auto"),
    // 'scheduled' → books not yet collected
    // 'marking'   → books collected, being marked now
    // 'returned'  → handed back, cycle complete
    status: text("status").notNull().default("scheduled"),
    collectDate: date("collect_date", { mode: "string" }).notNull(),
    collectPeriod: integer("collect_period"),
    handbackDate: date("handback_date", { mode: "string" }).notNull(),
    handbackPeriod: integer("handback_period"),
    totalBooks: integer("total_books").notNull().default(30),
    markedCount: integer("marked_count").notNull().default(0),
    dailyRate: integer("daily_rate").notNull().default(6),
    // locked plans survive a smart-planner regeneration
    locked: boolean("locked").notNull().default(false),
    // 'late' means the planner could not fit it inside the ideal window
    late: boolean("late").notNull().default(false),
    returnedAt: date("returned_at", { mode: "string" }),
    notes: text("notes").notNull().default(""),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("plans_user_idx").on(t.userId),
    index("plans_class_idx").on(t.classId),
    index("plans_status_idx").on(t.status),
  ],
);

// Specific weekdays when the teacher is not at work or has protected from marking.
// Weekends are already excluded by the scheduler; this table is for exceptions.
export const unavailableDates = pgTable(
  "unavailable_dates",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    date: date("date", { mode: "string" }).notNull(),
    reason: text("reason").notNull().default(""),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("unavailable_dates_user_date_idx").on(t.userId, t.date),
    index("unavailable_dates_user_idx").on(t.userId),
  ],
);

export const markingEntries = pgTable(
  "marking_entries",
  {
    id: serial("id").primaryKey(),
    planId: integer("plan_id")
      .notNull()
      .references(() => markingPlans.id, { onDelete: "cascade" }),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    date: date("date", { mode: "string" }).notNull(),
    count: integer("count").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("entries_plan_idx").on(t.planId),
    index("entries_user_idx").on(t.userId),
  ],
);

// Cheap + durable place for the photo of the paper timetable
export const timetablePhotos = pgTable("timetable_photos", {
  userId: integer("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  dataUrl: text("data_url").notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type ClassRow = typeof classes.$inferSelect;
export type SlotRow = typeof timetableSlots.$inferSelect;
export type PlanRow = typeof markingPlans.$inferSelect;
export type UnavailableDateRow = typeof unavailableDates.$inferSelect;
export type EntryRow = typeof markingEntries.$inferSelect;
export type SettingsRow = typeof userSettings.$inferSelect;
